artifacts_root: artifacts

# For data ingestion
data_ingestion:
  source_type: google_drive
  gdrive_folder_id: 1zo4eA6ce8xXYr_anl-b9RvqnHViQT1yp
  file_name: symptoms-diseases.csv

  artifacts_dir: artifacts
  raw_data_dir: artifacts/raw_data
  raw_data_path: artifacts/raw_data/symptoms-diseases.csv

# For data validation
data_validation:
  target_column: prognosis
  validation_dir: artifacts/data_validation
  validation_report_path: artifacts/data_validation/validation_report.json

# For data transformation
data_transformation:
  transformed_dir: artifacts/data_transformation
  cleaned_data_path: artifacts/data_transformation/cleaned_data.csv
  label_encoder_path: artifacts/data_transformation/label_encoder.pkl

#for model training
model_trainer:
  model_dir: artifacts/model_trainer
  trained_model_dir: artifacts/model_trainer
  model_report_path: artifacts/model_trainer/model_report.yaml

