artifacts_root: artifacts

#for data ingestion
data_ingestion:
  source_type: google_drive
  gdrive_folder_id: 1zo4eA6ce8xXYr_anl-b9RvqnHViQT1yp
  file_name: symptom_disease_dataset.csv

  artifacts_dir: artifacts
  raw_data_dir: artifacts/data_ingestion
  raw_data_path: artifacts/data_ingestion/raw_data.csv


#for data validation
data_validation:
  target_column: prognosis

  validation_dir: artifacts/data_validation
  validation_report_path: artifacts/data_validation/validation_report.json
