RandomForestClassifier:
  n_estimators: 200
  max_depth: 20
  min_samples_split: 5
  random_state: 42
  n_jobs: -1

LogisticRegression:
  max_iter: 2000
  solver: lbfgs
  n_jobs: -1

DecisionTreeClassifier:
  max_depth: 25
  min_samples_split: 5
  random_state: 42

XGBoost:
  n_estimators: 300
  learning_rate: 0.1
  max_depth: 8
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
